### ISSUE TITLE
Inconsistencies with DataPLANT on the main webpage

### ISSUE THREAD

**Issue by kdumschott** [nfdi4plants/nfdi4plants.github.io#104]
DataPLANT is formatted incorrectly under some headings on the main webpage. It's written as DataPlant under the community and the ARC headings.

**Comment by Brilator** [comment]
@CMR248

**Comment by Martin-Kuhl** [comment]
Found on landing page:

THE COMMUNITY
Fundamental research in plant science
**DataPlant** is primarily geared towards the needs of fundamental plant research ...
... As such **DataPlant** is especially adapter to large scale data sets be it omics science or


ANNOTATED RESEARCH CONTEXT
Understanding ARC publications
**DataPlant** will allow users to store their data in form of an annotated research context ...

**Comment by CMR248** [comment]
It should be fixed everywhere. If I missed something, feel free to reopen the issue.
