### ISSUE TITLE
Add logos of funders

### ISSUE THREAD

**Issue by andreaschrader** [nfdi4plants/nfdi4plants.github.io#109]
Suggestion: add logos of the funders in the footer of the website in addition to the link to the NFDI.

**Comment by fstein88** [comment]
Das DFG-Logo mit englischsprachiger Unterzeile inkl. Zusatz "Funded by" (https://www.dfg.de/de/service/logo-corporate-design)
Dateien: [dfg-logo-foerderung-international-data.zip](https://github.com/user-attachments/files/16581506/dfg-logo-foerderung-international-data.zip)

**Comment by Freymaurer** [comment]
Done!
