### ISSUE TITLE
Place to put developer information

### ISSUE THREAD

**Issue by HLWeil** [nfdi4plants/nfdi4plants.github.io#119]
Hey,
I'm currently working on an `graphical overview` of the `tool stack` we are developing at DataPlant. As far as I know, we currently have no place to put this kind of repository spanning information for developers. Maybe we could add some kind of developers section to the knowledge-base? 
In addition to the information about the different projects, we could also add general contribution guideslines to this section.

**Comment by Freymaurer** [comment]
This can always be added to the knowledgebase
