### ISSUE TITLE
Page rework

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/nfdi4plants.github.io#153]
this is currently under development and will be püart of this PR: https://github.com/nfdi4plants/nfdi4plants.github.io/pull/152 

- [x] About -> Community and partner; still missing content.
- [x] About -> Testimonials; formatting
- [x] About -> nfdi; missing "read more"
- [x] information -> news; fix news link
- [x] information -> events; fix events link
- [x] information -> knowledge base; fix link
- [ ] service -> sitemap not compatible with word doc(!)
- [ ] service -> arc; still needs work
- [x] service -> dataplan; fix link
- [x] service -> training; fix link
- [x] service -> templates; fix link
- [x] service -> data publication; add link for ARChive
- [x] service -> collect and structure; fix links and add file to sitemap!
- [x] #154
- [x] #155
- [ ] resources -> galaxy; missing link
- [x] resources -> for developers; formatting + subcontent
- [ ] resources -> styleguide; missing
- [ ] participation -> how to start; missing
- [x] support -> helpdesk; missing link
- [ ] support -> rdm; missing link to arc-rdm.org
- [x] support -> custom training; missing mailto: link
- [ ] support -> user support meeting from word file not on sitemap! not done!
- [ ] fix image aspect ratios

**Comment by kMutagene** [comment]
Note that the word doc and the repo is heavily out-of-sync, as it is to be expected. 

From now on i suggest documenting everything in this repo.

Also, the sitemap is out-of sync, and some subpages have missing content.

**Comment by kMutagene** [comment]
i think we can close this as we are approaching a vastly different launch than first envisioned, will follow up with a list of to dos after launch
