### ISSUE TITLE
Some notes on the new changes

### ISSUE THREAD

**Issue by HLWeil** [nfdi4plants/nfdi4plants.github.io#161]

**Comment by HLWeil** [comment]
Typo on the `About DataPLANT` page:

Should be "partners" with an "s".

**Comment by HLWeil** [comment]
Clicking on a link in the TOC jumps a bit too far?

<img width="313" alt="image" src="https://github.com/user-attachments/assets/8d952858-e9a3-4b2a-a417-42a1e4d46a56">

->

![image](https://github.com/user-attachments/assets/2875b55b-616f-41df-bb0a-66cf185f0d4a)

**Comment by HLWeil** [comment]
Should this be a link to website?

![image](https://github.com/user-attachments/assets/11dcf28f-74b9-4d3c-866d-3f9b580be8ea)

**Comment by HLWeil** [comment]
Missing closing bracket:
![image](https://github.com/user-attachments/assets/ddf141c7-4854-41a5-b6ee-69c20fc66f8f)

**Comment by HLWeil** [comment]
No content yet or component missing?

![image](https://github.com/user-attachments/assets/01e671ec-4718-444f-b570-39982624e776)

**Comment by HLWeil** [comment]
"task area leads" without the s after area

![image](https://github.com/user-attachments/assets/046d5ddf-9730-4e0e-8827-0106199f0da5)

Also different upper and lower casing between "Focus Area Leads" and "task area leads"

**Comment by HLWeil** [comment]
![image](https://github.com/user-attachments/assets/260a7b4c-d8e9-4836-80db-48ff5865b0e7)

Link to arc-registry?

**Comment by Freymaurer** [comment]
This is outdated, will close for now!
