### ISSUE TITLE
ideas for events page

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/nfdi4plants.github.io#173]
- [x] combine or differentiate tutor(s) and organizers / organization
- [x] Add contact, affiliation, etc. to tutors
- [ ] add contact cards for workshop organizers (similar to ongoing authors in knowledge base)
- [x] support recurrent meetings (e.g. data steward circle)
- [ ] reduce schema checks: e.g. if url is empty, ignore 
- [ ] Calendar View
  - collect all Events in calendar view
  - color code by category
- [x] search events by YAML tags
- [x] support svg images
- [x] the displayed times are shifted 2 hours on my devices (laptop and phone)
- [x] the filter buttons do not work smoothly
  - e.g. clicking "Conference" shows non-Conference Events

**Comment by Brilator** [comment]
FYI @Freymaurer

**Comment by Freymaurer** [comment]
@Brilator have a look at the current implementation, then we'll have to look into this again.

I like the idea of a calendar view!

**Comment by Brilator** [comment]
- [ ] the displayed times are shifted 2 hours on my devices (laptop and phone)

**Comment by Freymaurer** [comment]
> the displayed times are shifted 2 hours on my devices (laptop and phone)

DateTime must be given as UTC, it is then automatically converted to locale time by the website

**Comment by Freymaurer** [comment]
> add contact cards for workshop organizers (similar to ongoing authors in knowledge base)

Is this feature required? I can create such a thing, but then every tutor must be listed as a file in the website

> reduce schema checks: e.g. if url is empty, ignore

Need more info

> support svg images

Need more info

**Comment by Brilator** [comment]
On the other hand, we could populate a page of tutors / contributors based on tutor files.

**Comment by Freymaurer** [comment]
Can you give the exact frontmatter field, for which svg failed?

**Comment by Brilator** [comment]
Nevermind, that seemed to be an issue with svg coming from one specific software

**Comment by Freymaurer** [comment]
Will close this for now, not sure if i will have time for much more in this area
