### ISSUE TITLE
Community Map to-dos

### ISSUE THREAD

**Issue by kMutagene** [nfdi4plants/nfdi4plants.github.io#179]
- [x] refactor distinction of participating persons and projects
- [ ] update csv files of orgs/participants (cc @muehlhaus)
- [x] refactor institutions as their own csv/data model
- [x] add institution links to list
- [x] add links to tooltips

**Comment by fstein88** [comment]
I've just updated the participants.csv:

- added two missing participants
- removed a retired participant
- fixed  MLU entry since it was in German

**Comment by Freymaurer** [comment]
@kMutagene is this finsihed?

**Comment by kMutagene** [comment]
from a technical point yes, but i dont know if the list is complete now @muehlhaus @AngelaKranz ?

**Comment by fstein88** [comment]
I'm about to double check all the names. Already found a bunch of links that don't work anymore. I'll let you know once I'm done.

**Comment by fstein88** [comment]
Files are updated
