### ISSUE TITLE
Events to-dos

### ISSUE THREAD

**Issue by kMutagene** [nfdi4plants/nfdi4plants.github.io#196]
- [x] make "upcoming events" as prominent as "archive" on the /events page
- [x] implement reoccuring events ?

**Comment by Brilator** [comment]
+1 for reoccurring events

- Duplicating (and updating) multiple repetitive files is a mess
- Ideally implement via YAML tag "recurrence"  (options "single", "series" (for events that have day 1, day2, "recurrence") 
- for first iteration would suffice to just add the dates as array by hand 
- platinum would be something like this :D 


<img width="492" alt="Screenshot 2024-10-10 at 17 48 38" src="https://github.com/user-attachments/assets/d0124b68-3e7f-4ae5-9d6b-fe594cb4117d">

**Comment by Freymaurer** [comment]
Done! Will add something to the contribution guide!
