### ISSUE TITLE
[Add event]: Hands-on Workshop on FAIR Data Management Using ARCs

### ISSUE THREAD

**Issue by blaker42** [nfdi4plants/nfdi4plants.github.io#199]
### Event start time

2024-10-21T09:30:00

### Event end time

2024-10-23T15:00:00

### Event title

Hands-on Workshop on FAIR Data Management Using ARCs

### Organizer(s)

Bianca Laker

### Tutor(s)

Bianca Laker

### audience

Users

### Registration deadline

closed

### Max. number of seats

14

### Event mode

Online

### Event category

Training

### Description

The workshop covers the fundamentals of research data management and the principles of FAIR data. In the practical sessions, participants will use DataPLANT's ARCitect to structure a research project and SWATE for metadata annotation. The workshop is intended for members of the 'Ecology and Evolution of Intraspecific Chemodiversity in Plants' (Chemodiv) research unit.

**Comment by Brilator** [comment]
Hi Bianca, 
@Freymaurer finished the events page design. Your workshop is now on `main` and public, but might need some adaptations. 

https://nfdi4plants.github.io/events/2024-10-21_handson-fair-rdm/

**Comment by Freymaurer** [comment]
@blaker42 @Brilator can this be closed?

**Comment by blaker42** [comment]
If you can change the time to 9:00 am until 16:00, I am happy with the page.

**Comment by Brilator** [comment]
https://github.com/nfdi4plants/nfdi4plants.github.io/edit/main/src/content/events/2024-10-21_HandsOn-FAIR-RDM.md

**Comment by Freymaurer** [comment]
Done!
