### ISSUE TITLE
adapt event issue template

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/nfdi4plants.github.io#203]
Once the schema is fixed, the template needs to be updated and properly described.

**Comment by Freymaurer** [comment]
- This does not matter?
![image](https://github.com/user-attachments/assets/48a86210-1d80-4fdf-97f3-083208d4d72f)

- The template does not list the option for an external link
- The template might require a "note for the editor" field. In which users could directly address the event editor if they are unsure about fields or where to place what information

**Comment by Brilator** [comment]
> The template might require a "note for the editor" field. In which users could directly address the event editor if they are unsure about fields or where to place what information

I'd suggest to just use GitHub logic for that.

**Comment by Brilator** [comment]
> This does not matter?

Yes, I'll fix the validations for mandatory fields.
