### ISSUE TITLE
Unify names of tools & services

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/nfdi4plants.github.io#208]
- [x] `ARC Commander` (based on GH repo) or `ARCCommander` 
- [x] `Swate` (based on GH repo) or `SWATE`
- [x] `PLANTdataHUB` (based on plant journal paper) or `PlantDataHub` or `PLANTDataHUB`
- [x] `Knowledge Base` not `knowledgebase`

**Comment by Freymaurer** [comment]
> Swate (based on GH repo) or SWATE

`Swate`, not ~~`SWATE`~~

**Comment by Freymaurer** [comment]
done!
