### ISSUE TITLE
remove (content of) mainpagecards ?

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/nfdi4plants.github.io#209]
If I understand correctly, the mds in `src/content/mainpagecards` are just relevant to build the navbar? 

The text for those cards are in src/content/subpage? 
Is it possible to merge them?

**Comment by Freymaurer** [comment]
src/content/mainpagecards are only used for the level 1 content (landing/main/home page)

https://github.com/nfdi4plants/nfdi4plants.github.io/blob/main/CONTRIBUTING.md#page-structure

> Is it possible to merge them?

I wanted to do this, but to keep the approach more flexible we decided against.

**Comment by Freymaurer** [comment]
Will close for now, as mainpagecards content is used for level 1 content:
![image](https://github.com/user-attachments/assets/815c4567-494e-4a59-b65a-d9bc6c58b5de)
