### ISSUE TITLE
Youtube Icon

### ISSUE THREAD

**Issue by CMR248** [nfdi4plants/nfdi4plants.github.io#4]
Youtube icon should be added to the Landing Page.
Usage guidelines and download links can be found here:
[Markenressourcen Youtube](https://www.youtube.com/about/brand-resources/#logos-icons-colors/ "Usage guidelines and download links")

**Comment by CMR248** [comment]
Youtube icon should be added to the Landing Page. 
Usage guidelines and download links can be found here:
[](https://www.youtube.com/about/brand-resources/#logos-icons-colors)

**Comment by kMutagene** [comment]
closed via https://github.com/nfdi4plants/nfdi4plants.github.io/commit/ead2280a619cbb49f87dbc95a83a7d9631c20b33
