### ISSUE TITLE
Make "learn-more" sections more visible. 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/nfdi4plants.github.io#57]
I just by chance stumbled across the learn-more sections (https://nfdi4plants.de/content/learn-more/***) again. 
They're great (apart from some graphics rendering issues) and I think they need to be more prominent. 

I would suggest to either give them their own main page "Learn More" in the top navbar. 
and / or add some hover-over menu in the navbar to directly navigate to sub-topics (could also be relevant for other content). 

<img width="600" alt="Screen Shot 2022-02-16 at 09 39 09" src="https://user-images.githubusercontent.com/16229676/154228001-82a132aa-ac4f-4270-92c7-0cb1e2d63cdc.png">

**Comment by CMR248** [comment]
Already integrated in [Web-components](https://github.com/nfdi4plants/web-components). All that is missing now is the integration of these into the website.
