### ISSUE TITLE
Redering in FF is suboptimal

### ISSUE THREAD

**Issue by bgruening** [nfdi4plants/nfdi4plants.github.io#79]
This site: https://nfdi4plants.org/content/learn-more/annotated-research-context.html looks like

![grafik](https://user-images.githubusercontent.com/469983/170954853-7f6b0e77-fe73-4a44-b41a-fdb54500a532.png)

in Firefox and Chrome.

**Comment by CMR248** [comment]
Unfortunately, I can't reproduce the problem. Could you check again if the problem has been fixed?

**Comment by bgruening** [comment]
Seems to be fixed :)
Thanks.
