### ISSUE TITLE
Issue with user-added TOC 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/nfdi4plants.github.io#89]
@Freymaurer, can you please check the TOC in the Quickstart? https://github.com/nfdi4plants/nfdi4plants.github.io/edit/main/src/content/docs/quickstart_arc.md

The heading "The Minimalist's ARC-QuickStart" isn't parsed properly. GH flavored markdown works.

**Comment by Freymaurer** [comment]
Good catch, i fixed it 👍

**Comment by Brilator** [comment]
Sweet!
